# Input file directory
input_dir: "input"

# Output file directory
output_dir: "output"

# Temporary file directory
temp_dir: "temp"

# Bed service provider, optional (COS)
pic_bed: "cos"

# Tencent Cloud COS Configuration
cos_config:
  bucket_name: "yvling-typora-image-125xxxxxxx"
  bucket_area: "ap-nanjing"
  pic_path: "typora"
  secret_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  secret_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Yuque Configuration
yuque_config:
  _yuque_session: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  yuque_ctoken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  export_path: "yuque_export"